#ifndef DOOM_FRAMES_H
#define DOOM_FRAMES_H

#include <stdint.h>

/* Generated by tools/video_to_frames.py — do not hand-edit. */

extern const uint32_t DOOM_FRAME_COUNT;
extern const uint32_t DOOM_FPS;

/* Decompress frame idx into OLED_Framebuffer(). Call OLED_Update() after. */
void DoomFrames_Blit(uint32_t idx);

#endif
